#!/bin/bash

WRITE_DIR="/pool/torrent/magnets/"
MAGNET="${1:-x}"

if [[ "${MAGNET}" == "x" ]]; then
  echo "Usage: ./$0 \"<magnet-link>\""
  exit 255
fi

WRITE_FILE="$(echo ${MAGNET} | grep -oE '=([^=]+)' | head -n2 | tail -n 1).magnet"
WRITE="${WRITE_DIR}${WRITE_FILE:1}"

echo -en "Writing Magnet Link\n  File: \"${WRITE}\"\n  With: \"${1}\"\n"
echo "${1}" > "${WRITE}"
